



POST http://localhost:9001/vehicles/bulk-insert
Content-Type: application/json

[
  {
    "objectId": "0A0ZKrHx9O",
    "year": "1997",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "1dar3l5anK",
    "year": "2015",
    "make": "Hyundai",
    "model": "M02",
    "category": "C02",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "1dRys95AGL",
    "year": "2016",
    "make": "Hyundai",
    "model": "M03",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "1NBkr9sVFP",
    "year": "2012",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.016Z",
    "updatedAt": "2020-01-27T21:32:33.016Z"
  },
  {
    "objectId": "1vmTpQbKhh",
    "year": "1998",
    "make": "Hyundai",
    "model": "M04",
    "category": "C03",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "1XzdqSU5YY",
    "year": "2005",
    "make": "Hyundai",
    "model": "M05",
    "category": "C03",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "2FHoHPFeDw",
    "year": "2013",
    "make": "Hyundai",
    "model": "M06",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.016Z",
    "updatedAt": "2020-01-27T21:32:33.016Z"
  },
  {
    "objectId": "2JgDIjD1jH",
    "year": "2006",
    "make": "Hyundai",
    "model": "M06",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "2KFSHGNpt2",
    "year": "2019",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "2r2tmmxhsD",
    "year": "2018",
    "make": "Hyundai",
    "model": "M07",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "32heKtpU5J",
    "year": "2017",
    "make": "Hyundai",
    "model": "M05",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "3CIFSoI7FM",
    "year": "2008",
    "make": "Hyundai",
    "model": "M08",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "3NAnn8kapI",
    "year": "2018",
    "make": "Hyundai",
    "model": "M09",
    "category": "C05",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "3nCoJq1Gco",
    "year": "2010",
    "make": "Hyundai",
    "model": "M05",
    "category": "C06",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "3vB2YqJ8gn",
    "year": "2014",
    "make": "Hyundai",
    "model": "M04",
    "category": "C03",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "47fxitYJgs",
    "year": "2007",
    "make": "Hyundai",
    "model": "M08",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "4AszKI9uDx",
    "year": "2010",
    "make": "Hyundai",
    "model": "M08",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "4pF4zuURri",
    "year": "2018",
    "make": "Hyundai",
    "model": "M10",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "4QsJWyXKTQ",
    "year": "2015",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "5biDTU1M84",
    "year": "2018",
    "make": "Hyundai",
    "model": "M11",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "5Jo9olrybh",
    "year": "2012",
    "make": "Hyundai",
    "model": "M05",
    "category": "C07",
    "createdAt": "2020-01-27T21:32:33.016Z",
    "updatedAt": "2020-01-27T21:32:33.016Z"
  },
  {
    "objectId": "5u0fMmzbVJ",
    "year": "2016",
    "make": "Hyundai",
    "model": "M06",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "5zZQgjervc",
    "year": "2020",
    "make": "Hyundai",
    "model": "M04",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "63oyOPuZuJ",
    "year": "2016",
    "make": "Hyundai",
    "model": "M12",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "6NY4Gy4jge",
    "year": "1994",
    "make": "Hyundai",
    "model": "M13",
    "category": "C03",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "6QydypW36V",
    "year": "2020",
    "make": "Hyundai",
    "model": "M14",
    "category": "C05",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "6TUgfniSgl",
    "year": "2011",
    "make": "Hyundai",
    "model": "M04",
    "category": "C08",
    "createdAt": "2020-01-27T21:32:33.016Z",
    "updatedAt": "2020-01-27T21:32:33.016Z"
  },
  {
    "objectId": "6uwzzGbWH1",
    "year": "2014",
    "make": "Hyundai",
    "model": "M12",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "6zTU8Lx8Rs",
    "year": "2015",
    "make": "Hyundai",
    "model": "M06",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "7Bfr0oBRHD",
    "year": "2005",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "7DBjPCPNR7",
    "year": "2019",
    "make": "Hyundai",
    "model": "M04",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "7iYSWRvbuT",
    "year": "2015",
    "make": "Hyundai",
    "model": "M15",
    "category": "C05",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "7zMcF3GJmT",
    "year": "2018",
    "make": "Hyundai",
    "model": "M16",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "8bdhZoHlkD",
    "year": "1998",
    "make": "Hyundai",
    "model": "M05",
    "category": "C07",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "8chN44lyXf",
    "year": "2001",
    "make": "Hyundai",
    "model": "M17",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "8dV1hBn4zJ",
    "year": "2020",
    "make": "Hyundai",
    "model": "M06",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "8ztl0qBpJw",
    "year": "2007",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "9OWwfo8BBn",
    "year": "2017",
    "make": "Hyundai",
    "model": "M15",
    "category": "C05",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "9Qo8KOFckr",
    "year": "1994",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "ABPJGrdoUz",
    "year": "2018",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "AcVbE0M4xx",
    "year": "2012",
    "make": "Hyundai",
    "model": "M18",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.016Z",
    "updatedAt": "2020-01-27T21:32:33.016Z"
  },
  {
    "objectId": "AgHyp4ztmO",
    "year": "2013",
    "make": "Hyundai",
    "model": "M05",
    "category": "C09",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "ANg79HMNKl",
    "year": "2019",
    "make": "Hyundai",
    "model": "M11",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "aPytwPTzRY",
    "year": "2012",
    "make": "Hyundai",
    "model": "M12",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.016Z",
    "updatedAt": "2020-01-27T21:32:33.016Z"
  },
  {
    "objectId": "aQQMqBD7rq",
    "year": "2012",
    "make": "Hyundai",
    "model": "M19",
    "category": "C02",
    "createdAt": "2020-01-27T21:32:33.016Z",
    "updatedAt": "2020-01-27T21:32:33.016Z"
  },
  {
    "objectId": "athZz0r21W",
    "year": "2010",
    "make": "Hyundai",
    "model": "M02",
    "category": "C02",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "ATqjsK8UJq",
    "year": "2019",
    "make": "Hyundai",
    "model": "M20",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "AtVYNMMBaW",
    "year": "2019",
    "make": "Hyundai",
    "model": "M07",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "awfbpNiADr",
    "year": "1995",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "B0Y6oeEiLI",
    "year": "2004",
    "make": "Hyundai",
    "model": "M21",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "bAT7sGb4RD",
    "year": "2017",
    "make": "Hyundai",
    "model": "M19",
    "category": "C02",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "bbsR8CdFpI",
    "year": "2013",
    "make": "Hyundai",
    "model": "M18",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "BD5dPGzVJK",
    "year": "2016",
    "make": "Hyundai",
    "model": "M15",
    "category": "C05",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "bJgJNvBGL2",
    "year": "2009",
    "make": "Hyundai",
    "model": "M11",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "bXglWNlK0D",
    "year": "2005",
    "make": "Hyundai",
    "model": "M22",
    "category": "C02",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "C0aTxWDb05",
    "year": "2004",
    "make": "Hyundai",
    "model": "M05",
    "category": "C08",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "Cadtjt5Osw",
    "year": "2009",
    "make": "Hyundai",
    "model": "M03",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "CaFnIewZpC",
    "year": "2004",
    "make": "Hyundai",
    "model": "M22",
    "category": "C02",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "cB3M3eUfEN",
    "year": "2003",
    "make": "Hyundai",
    "model": "M05",
    "category": "C08",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "cCdw6msnxz",
    "year": "2016",
    "make": "Hyundai",
    "model": "M02",
    "category": "C02",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "CCjNd2Yp3Y",
    "year": "1996",
    "make": "Hyundai",
    "model": "M05",
    "category": "C07",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "cCznXED7a7",
    "year": "2004",
    "make": "Hyundai",
    "model": "M04",
    "category": "C03",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "cdMyKPp1w7",
    "year": "2012",
    "make": "Hyundai",
    "model": "M04",
    "category": "C08",
    "createdAt": "2020-01-27T21:32:33.016Z",
    "updatedAt": "2020-01-27T21:32:33.016Z"
  },
  {
    "objectId": "chX621aMDh",
    "year": "2012",
    "make": "Hyundai",
    "model": "M11",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.016Z",
    "updatedAt": "2020-01-27T21:32:33.016Z"
  },
  {
    "objectId": "cQlDWUTeHX",
    "year": "2013",
    "make": "Hyundai",
    "model": "M12",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "CWskNbpyn1",
    "year": "2017",
    "make": "Hyundai",
    "model": "M23",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "cYBOinhb39",
    "year": "2010",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "D7g29Hoz9D",
    "year": "2014",
    "make": "Hyundai",
    "model": "M16",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "dahaReqEkA",
    "year": "1999",
    "make": "Hyundai",
    "model": "M04",
    "category": "C03",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "dgYYaskFjO",
    "year": "2016",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "di6aCoJhGD",
    "year": "2012",
    "make": "Hyundai",
    "model": "M06",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.016Z",
    "updatedAt": "2020-01-27T21:32:33.016Z"
  },
  {
    "objectId": "DmLaGUDZHd",
    "year": "2019",
    "make": "Hyundai",
    "model": "M24",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "dvdP3OsLHS",
    "year": "1999",
    "make": "Hyundai",
    "model": "M22",
    "category": "C05",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "DW9BkvXVpO",
    "year": "1992",
    "make": "Hyundai",
    "model": "M05",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "dyIzyHbqXd",
    "year": "2016",
    "make": "Hyundai",
    "model": "M04",
    "category": "C03",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "DZcHElTBir",
    "year": "2002",
    "make": "Hyundai",
    "model": "M04",
    "category": "C03",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "E2FvzJou9h",
    "year": "2019",
    "make": "Hyundai",
    "model": "M09",
    "category": "C05",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "e6AbA1TAqv",
    "year": "2013",
    "make": "Hyundai",
    "model": "M19",
    "category": "C02",
    "createdAt": "2020-01-27T21:32:33.016Z",
    "updatedAt": "2020-01-27T21:32:33.016Z"
  },
  {
    "objectId": "eBFJCY7diq",
    "year": "2007",
    "make": "Hyundai",
    "model": "M04",
    "category": "C03",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "eCJ9pnSjW9",
    "year": "1998",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "EGGXKACo3i",
    "year": "2020",
    "make": "Hyundai",
    "model": "M10",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "EiDwJtUewa",
    "year": "2002",
    "make": "Hyundai",
    "model": "M05",
    "category": "C08",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "ePH47CWm8v",
    "year": "2008",
    "make": "Hyundai",
    "model": "M05",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "ETPxI3Iohw",
    "year": "2017",
    "make": "Hyundai",
    "model": "M06",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "euWbJmL8Kb",
    "year": "2003",
    "make": "Hyundai",
    "model": "M04",
    "category": "C03",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "ewF4YQornC",
    "year": "2009",
    "make": "Hyundai",
    "model": "M08",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "Ey8WmTiicn",
    "year": "1995",
    "make": "Hyundai",
    "model": "M25",
    "category": "C02",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "eZdPlE0Aa7",
    "year": "1996",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "FAewENzoQ9",
    "year": "2019",
    "make": "Hyundai",
    "model": "M05",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "Ffg7Pne705",
    "year": "2015",
    "make": "Hyundai",
    "model": "M12",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "fIusqVrcV5",
    "year": "2018",
    "make": "Hyundai",
    "model": "M14",
    "category": "C05",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "FjIdYot0kq",
    "year": "2017",
    "make": "Hyundai",
    "model": "M26",
    "category": "C05",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "FjsHQWBK2G",
    "year": "2008",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "FKhTHbhb4v",
    "year": "2012",
    "make": "Hyundai",
    "model": "M03",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.016Z",
    "updatedAt": "2020-01-27T21:32:33.016Z"
  },
  {
    "objectId": "GA7o1X7hXF",
    "year": "2019",
    "make": "Hyundai",
    "model": "M15",
    "category": "C05",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "gEVApn7Roo",
    "year": "2009",
    "make": "Hyundai",
    "model": "M05",
    "category": "C07",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "GFY81JICG3",
    "year": "2006",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "gKZYQWE5Kq",
    "year": "2016",
    "make": "Hyundai",
    "model": "M19",
    "category": "C02",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "Gm6Dd0W4CK",
    "year": "2018",
    "make": "Hyundai",
    "model": "M05",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "gxePGCjKQX",
    "year": "2016",
    "make": "Hyundai",
    "model": "M07",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "H29PC5iaEM",
    "year": "2011",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.016Z",
    "updatedAt": "2020-01-27T21:32:33.016Z"
  },
  {
    "objectId": "hA93xjwyG1",
    "year": "2012",
    "make": "Hyundai",
    "model": "M02",
    "category": "C02",
    "createdAt": "2020-01-27T21:32:33.016Z",
    "updatedAt": "2020-01-27T21:32:33.016Z"
  },
  {
    "objectId": "HAaQyR2mpU",
    "year": "2010",
    "make": "Hyundai",
    "model": "M03",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "HaYJEoCCLg",
    "year": "1997",
    "make": "Hyundai",
    "model": "M04",
    "category": "C03",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "HJ4smmaJIZ",
    "year": "2014",
    "make": "Hyundai",
    "model": "M03",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "HNLtl3Gbij",
    "year": "2014",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "hUSQgVHZ9n",
    "year": "1994",
    "make": "Hyundai",
    "model": "M25",
    "category": "C02",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "HXyVgokzX0",
    "year": "2010",
    "make": "Hyundai",
    "model": "M11",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "iBhh8O4gcx",
    "year": "2019",
    "make": "Hyundai",
    "model": "M14",
    "category": "C05",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "IkScSb8fqj",
    "year": "2010",
    "make": "Hyundai",
    "model": "M04",
    "category": "C03",
    "createdAt": "2020-01-27T21:32:33.016Z",
    "updatedAt": "2020-01-27T21:32:33.016Z"
  },
  {
    "objectId": "iP4dGU0nBr",
    "year": "2004",
    "make": "Hyundai",
    "model": "M11",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "IrK3u9YD7a",
    "year": "1994",
    "make": "Hyundai",
    "model": "M05",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "izNTsqKJ2f",
    "year": "2015",
    "make": "Hyundai",
    "model": "M04",
    "category": "C08",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "j96og6tvZn",
    "year": "2015",
    "make": "Hyundai",
    "model": "M19",
    "category": "C02",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "JbPTeaHBku",
    "year": "2015",
    "make": "Hyundai",
    "model": "M03",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "JCwBAQS1eA",
    "year": "2011",
    "make": "Hyundai",
    "model": "M06",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.016Z",
    "updatedAt": "2020-01-27T21:32:33.016Z"
  },
  {
    "objectId": "jHB4FBLmv0",
    "year": "2006",
    "make": "Hyundai",
    "model": "M22",
    "category": "C02",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "Jrezu6Oi7P",
    "year": "2019",
    "make": "Hyundai",
    "model": "M27",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "jtQ2ASxMIj",
    "year": "2004",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "K0BtuzisaB",
    "year": "2008",
    "make": "Hyundai",
    "model": "M28",
    "category": "C10",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "K2mrH8bktF",
    "year": "2020",
    "make": "Hyundai",
    "model": "M05",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "K2qmbZu8St",
    "year": "2018",
    "make": "Hyundai",
    "model": "M06",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "KgA3MOANwo",
    "year": "1997",
    "make": "Hyundai",
    "model": "M05",
    "category": "C06",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "kLCjvMl7i3",
    "year": "2000",
    "make": "Hyundai",
    "model": "M22",
    "category": "C05",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "Knrc8Ln7vM",
    "year": "2009",
    "make": "Hyundai",
    "model": "M06",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "kphYGfvXOH",
    "year": "2011",
    "make": "Hyundai",
    "model": "M12",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.016Z",
    "updatedAt": "2020-01-27T21:32:33.016Z"
  },
  {
    "objectId": "LD89x8fBDV",
    "year": "2011",
    "make": "Hyundai",
    "model": "M02",
    "category": "C02",
    "createdAt": "2020-01-27T21:32:33.016Z",
    "updatedAt": "2020-01-27T21:32:33.016Z"
  },
  {
    "objectId": "lKK1RKykPQ",
    "year": "1992",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "lMoBjWyFoj",
    "year": "2011",
    "make": "Hyundai",
    "model": "M08",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.016Z",
    "updatedAt": "2020-01-27T21:32:33.016Z"
  },
  {
    "objectId": "lxl9XuVoZX",
    "year": "2014",
    "make": "Hyundai",
    "model": "M06",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "M4hFgDHNb3",
    "year": "2020",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "m63nbAlYdb",
    "year": "2015",
    "make": "Hyundai",
    "model": "M16",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "mbG1xhUMe8",
    "year": "2003",
    "make": "Hyundai",
    "model": "M21",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "mCHDiuFrpA",
    "year": "2013",
    "make": "Hyundai",
    "model": "M04",
    "category": "C08",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "mEIihaVaRo",
    "year": "2009",
    "make": "Hyundai",
    "model": "M04",
    "category": "C03",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "MGzb1tuR3r",
    "year": "2017",
    "make": "Hyundai",
    "model": "M18",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "MrxcC6J7XP",
    "year": "2011",
    "make": "Hyundai",
    "model": "M18",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.016Z",
    "updatedAt": "2020-01-27T21:32:33.016Z"
  },
  {
    "objectId": "MWVCkTF3FA",
    "year": "2012",
    "make": "Hyundai",
    "model": "M08",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.016Z",
    "updatedAt": "2020-01-27T21:32:33.016Z"
  },
  {
    "objectId": "n0EPJo5JMu",
    "year": "1992",
    "make": "Hyundai",
    "model": "M13",
    "category": "C08",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "N5XfUD1mlg",
    "year": "2005",
    "make": "Hyundai",
    "model": "M11",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "n636NXdblc",
    "year": "1999",
    "make": "Hyundai",
    "model": "M05",
    "category": "C07",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "N6K1CzYTtN",
    "year": "2020",
    "make": "Hyundai",
    "model": "M15",
    "category": "C05",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "nAYflXbMa6",
    "year": "2017",
    "make": "Hyundai",
    "model": "M09",
    "category": "C05",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "NCNWyceTXY",
    "year": "2008",
    "make": "Hyundai",
    "model": "M04",
    "category": "C03",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "nDBcCCmvhN",
    "year": "2007",
    "make": "Hyundai",
    "model": "M11",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "nFY3wnDpAa",
    "year": "2003",
    "make": "Hyundai",
    "model": "M11",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "NQLK06JTA4",
    "year": "2006",
    "make": "Hyundai",
    "model": "M05",
    "category": "C03",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "nTkGSOoFYG",
    "year": "2020",
    "make": "Hyundai",
    "model": "M29",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "NyjbdDtrXQ",
    "year": "1998",
    "make": "Hyundai",
    "model": "M22",
    "category": "C05",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "nyy3FtWmCS",
    "year": "2001",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "o3o545OGFu",
    "year": "2006",
    "make": "Hyundai",
    "model": "M11",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "oBuK1unAQV",
    "year": "2018",
    "make": "Hyundai",
    "model": "M04",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "OHE3YQOKV3",
    "year": "2015",
    "make": "Hyundai",
    "model": "M05",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "OJ4HheLJp0",
    "year": "2014",
    "make": "Hyundai",
    "model": "M18",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "OJGk7vBuSN",
    "year": "2008",
    "make": "Hyundai",
    "model": "M11",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "p3ZE2dexD7",
    "year": "2010",
    "make": "Hyundai",
    "model": "M06",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "Perv6488b6",
    "year": "1995",
    "make": "Hyundai",
    "model": "M05",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "PF2TrDgZHm",
    "year": "2016",
    "make": "Hyundai",
    "model": "M24",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "pGTr9WZIOB",
    "year": "2007",
    "make": "Hyundai",
    "model": "M05",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "pKa7CCxO9u",
    "year": "2016",
    "make": "Hyundai",
    "model": "M18",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "PLI8HMMQBP",
    "year": "2013",
    "make": "Hyundai",
    "model": "M02",
    "category": "C02",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "pPEDpMdjEN",
    "year": "2003",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "pPWRlo2Kj4",
    "year": "2016",
    "make": "Hyundai",
    "model": "M11",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "PrqaeMg0ZS",
    "year": "1996",
    "make": "Hyundai",
    "model": "M04",
    "category": "C03",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "pTQg95KIk8",
    "year": "2002",
    "make": "Hyundai",
    "model": "M11",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "PYBxHDGIj4",
    "year": "2017",
    "make": "Hyundai",
    "model": "M11",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "PZI8Xe7ISf",
    "year": "2002",
    "make": "Hyundai",
    "model": "M21",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "Q4VCKpXBEi",
    "year": "2017",
    "make": "Hyundai",
    "model": "M04",
    "category": "C08",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "qEN2NIAKXf",
    "year": "2017",
    "make": "Hyundai",
    "model": "M16",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "qMjSaHp5uG",
    "year": "1993",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "qNjAJoDzQe",
    "year": "2019",
    "make": "Hyundai",
    "model": "M10",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "qqdtahpNjA",
    "year": "1993",
    "make": "Hyundai",
    "model": "M05",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "QRlnuSGGnv",
    "year": "2019",
    "make": "Hyundai",
    "model": "M19",
    "category": "C02",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "RBZ3wh1gYL",
    "year": "1997",
    "make": "Hyundai",
    "model": "M22",
    "category": "C05",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "rHdvkVlFMT",
    "year": "1992",
    "make": "Hyundai",
    "model": "M25",
    "category": "C02",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "RHUGNeUR0X",
    "year": "2007",
    "make": "Hyundai",
    "model": "M28",
    "category": "C10",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "RNIDtnhmW0",
    "year": "2017",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "RS14heNRIX",
    "year": "2003",
    "make": "Hyundai",
    "model": "M22",
    "category": "C02",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "rxFi0qFXzz",
    "year": "2008",
    "make": "Hyundai",
    "model": "M22",
    "category": "C05",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "s4HjnQiZJO",
    "year": "2017",
    "make": "Hyundai",
    "model": "M07",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "s5aFovwbTa",
    "year": "2018",
    "make": "Hyundai",
    "model": "M15",
    "category": "C05",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "S6DM0c2JkP",
    "year": "2020",
    "make": "Hyundai",
    "model": "M30",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "S6zczzhT5D",
    "year": "2014",
    "make": "Hyundai",
    "model": "M19",
    "category": "C02",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "sBmCy7aIJ1",
    "year": "2010",
    "make": "Hyundai",
    "model": "M18",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "SBszGLz939",
    "year": "2020",
    "make": "Hyundai",
    "model": "M19",
    "category": "C02",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "sLpNG0ZedH",
    "year": "2020",
    "make": "Hyundai",
    "model": "M27",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "SM8XrQP89M",
    "year": "2005",
    "make": "Hyundai",
    "model": "M04",
    "category": "C03",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "stDrtEYggV",
    "year": "2016",
    "make": "Hyundai",
    "model": "M16",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "SUhQ9YmfKi",
    "year": "2018",
    "make": "Hyundai",
    "model": "M24",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "svj52hCW3c",
    "year": "2008",
    "make": "Hyundai",
    "model": "M18",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "sy0evDfkCN",
    "year": "1999",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "T5rXe9xHUJ",
    "year": "2015",
    "make": "Hyundai",
    "model": "M11",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "T98CHtCVWh",
    "year": "2007",
    "make": "Hyundai",
    "model": "M18",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "tcPNf7pjKa",
    "year": "2001",
    "make": "Hyundai",
    "model": "M04",
    "category": "C03",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "ThlCZQJ7I0",
    "year": "2000",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.050Z",
    "updatedAt": "2020-01-27T21:32:33.050Z"
  },
  {
    "objectId": "tPFB6ZXAca",
    "year": "2008",
    "make": "Hyundai",
    "model": "M06",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "TqRsnOZnts",
    "year": "2016",
    "make": "Hyundai",
    "model": "M05",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "TsN41Dczzf",
    "year": "2000",
    "make": "Hyundai",
    "model": "M05",
    "category": "C06",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "U1HFnZh7YB",
    "year": "2011",
    "make": "Hyundai",
    "model": "M05",
    "category": "C06",
    "createdAt": "2020-01-27T21:32:33.016Z",
    "updatedAt": "2020-01-27T21:32:33.016Z"
  },
  {
    "objectId": "u1LFQend7A",
    "year": "2019",
    "make": "Hyundai",
    "model": "M29",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "U4eQBVvF42",
    "year": "2019",
    "make": "Hyundai",
    "model": "M06",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "U5ckQ3lZC5",
    "year": "2001",
    "make": "Hyundai",
    "model": "M05",
    "category": "C03",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "UF8gJ8QjsC",
    "year": "2013",
    "make": "Hyundai",
    "model": "M16",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.016Z",
    "updatedAt": "2020-01-27T21:32:33.016Z"
  },
  {
    "objectId": "uicvIjp9uJ",
    "year": "2017",
    "make": "Hyundai",
    "model": "M24",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "uqmm0W0eTu",
    "year": "2013",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.016Z",
    "updatedAt": "2020-01-27T21:32:33.016Z"
  },
  {
    "objectId": "uWYjGhrmEo",
    "year": "2006",
    "make": "Hyundai",
    "model": "M18",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "v2haiREzLG",
    "year": "2005",
    "make": "Hyundai",
    "model": "M06",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "V82zWI1R2q",
    "year": "2013",
    "make": "Hyundai",
    "model": "M11",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.016Z",
    "updatedAt": "2020-01-27T21:32:33.016Z"
  },
  {
    "objectId": "VEfwoD7ISE",
    "year": "2014",
    "make": "Hyundai",
    "model": "M05",
    "category": "C11",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "vJiEQcykmW",
    "year": "2016",
    "make": "Hyundai",
    "model": "M23",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "VnXczeFbJc",
    "year": "2009",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "vODe5VU0Ly",
    "year": "2014",
    "make": "Hyundai",
    "model": "M02",
    "category": "C02",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "VZivi9zmOp",
    "year": "2005",
    "make": "Hyundai",
    "model": "M21",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "vzRcv0f2WT",
    "year": "2020",
    "make": "Hyundai",
    "model": "M11",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "w81PJEnjE5",
    "year": "2013",
    "make": "Hyundai",
    "model": "M03",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "wkd2zta8Yb",
    "year": "2009",
    "make": "Hyundai",
    "model": "M18",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "wyBjE5k4sS",
    "year": "2001",
    "make": "Hyundai",
    "model": "M11",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "XEDI4IPxG6",
    "year": "2000",
    "make": "Hyundai",
    "model": "M04",
    "category": "C03",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "XFMPt0AJNq",
    "year": "2007",
    "make": "Hyundai",
    "model": "M22",
    "category": "C02",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "xiTo0Hwd8D",
    "year": "1993",
    "make": "Hyundai",
    "model": "M25",
    "category": "C02",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "xKIUW5N21A",
    "year": "2015",
    "make": "Hyundai",
    "model": "M23",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "XNafaMCAnf",
    "year": "1993",
    "make": "Hyundai",
    "model": "M13",
    "category": "C03",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "Y3GJ8K4M4S",
    "year": "2020",
    "make": "Hyundai",
    "model": "M31",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "yj71ixPalB",
    "year": "1995",
    "make": "Hyundai",
    "model": "M04",
    "category": "C03",
    "createdAt": "2020-01-27T21:32:33.051Z",
    "updatedAt": "2020-01-27T21:32:33.051Z"
  },
  {
    "objectId": "yNKB7w6nkT",
    "year": "2018",
    "make": "Hyundai",
    "model": "M26",
    "category": "C05",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "ypb173dGnI",
    "year": "2006",
    "make": "Hyundai",
    "model": "M04",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "YqtQqwBrFX",
    "year": "2001",
    "make": "Hyundai",
    "model": "M22",
    "category": "C05",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "yXd7x9cE78",
    "year": "2007",
    "make": "Hyundai",
    "model": "M06",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "ZCg1KqNdCM",
    "year": "2014",
    "make": "Hyundai",
    "model": "M11",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "ZdDTXVY3yB",
    "year": "2011",
    "make": "Hyundai",
    "model": "M11",
    "category": "C04",
    "createdAt": "2020-01-27T21:32:33.016Z",
    "updatedAt": "2020-01-27T21:32:33.016Z"
  },
  {
    "objectId": "zgmKmj3CBJ",
    "year": "2019",
    "make": "Hyundai",
    "model": "M26",
    "category": "C05",
    "createdAt": "2020-01-27T21:32:32.760Z",
    "updatedAt": "2020-01-27T21:32:32.760Z"
  },
  {
    "objectId": "zhS1biD6v6",
    "year": "2002",
    "make": "Hyundai",
    "model": "M01",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.017Z",
    "updatedAt": "2020-01-27T21:32:33.017Z"
  },
  {
    "objectId": "ZNGkqGGGgr",
    "year": "2015",
    "make": "Hyundai",
    "model": "M18",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:32.761Z",
    "updatedAt": "2020-01-27T21:32:32.761Z"
  },
  {
    "objectId": "zOw956ekQL",
    "year": "2011",
    "make": "Hyundai",
    "model": "M03",
    "category": "C01",
    "createdAt": "2020-01-27T21:32:33.016Z",
    "updatedAt": "2020-01-27T21:32:33.016Z"
  }
]

