apiVersion: v1
kind: Service

metadata:
  name: vehicle-api-svc
  namespace: vehicle
spec:
  selector:
    app: vehicle-api

  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
   # nodePort: 30001
  #type: NodePort



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-api
  namespace: vehicle
  labels:
    app: vehicle-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vehicle-api
  template:
    metadata:
      labels:
        app: vehicle-api
    spec:
      containers:
      - name: vehicle-api
        image: vehicle-api
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 9001
        volumeMounts:
        - name: log-volume
          mountPath: /logs

      - name: fluent-bit
        image: fluent/fluent-bit
        volumeMounts:
        - name: log-volume
          mountPath: /logs
        - name: config
          mountPath: /fluent-bit/etc/fluent-bit.conf
          subPath: fluent-bit.conf
        - name: config
          mountPath: /fluent-bit/etc/parsers_springboot.conf
          subPath: parsers_springboot.conf
      volumes:
      - name: log-volume
        emptyDir: {}
      - name: config
        configMap:
          name: fluent-bit-config
